image: registry.gitlab.com/josef.stach/aws-cdk-lambda-asset/ci-lambda

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  XDG_CACHE_HOME: "$CI_PROJECT_DIR/.cache/poetry"
  PYTHONPATH: ${CI_PROJECT_DIR}

before_script:
  - pip install -U pip

stages:
  - build
  - test

code_quality:
  stage: test
  script: |
    pip install -U flake8 flake8-builtins flake8-bandit flake8-codeclimate flake8-mypy pep8-naming flake8-comprehensions flake8-import-order
    python -m flake8 --format=codeclimate --exit-zero ${CI_PROJECT_NAME//-/_} | \
    python -c 'import fileinput; print("[",end="");print(",".join([l.strip() for l in fileinput.input()]));print("]",end="")' > gl-code-quality-report.json
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
  only:
    - branches
    - tags
    - master
    - merge_requests

test:
  script: |
    poetry install
    poetry run pytest --cov-report term-missing --cov=${CI_PROJECT_NAME//-/_} tests
  artifacts:
    reports:
      junit: junit.xml
  coverage: '/TOTAL.*\s+(\d+%)$/'
  only:
    - branches
    - tags
    - master
    - merge_requests
