name: Branch Test

on:
    pull_request:
        types: [assigned, opened, synchronize, reopened]

jobs:
    versioning:
        name: Versioning Compliance
        runs-on: ubuntu-latest

        steps:
            - uses: amannn/action-semantic-pull-request@v5
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  validateSingleCommit: true

    configure-python:
        name: Run tests
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - name: ↗️ Check out repository
              uses: actions/checkout@v2

            # Set up Python
            - name: Set up Python env
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9

            - name: 🐍 Set up cache 📦
              uses: actions/cache@v3
              with:
                  path: |
                      .venv
                      ~/.local
                  key: ${{ runner.os }}-3.9-poetry-${{ hashFiles('**/poetry.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-3.9-poetry-

            - name: Install Poetry
              uses: snok/install-poetry@v1

            - name: Install Python dependencies
              run: |
                  poetry install

            - name: Run tests
              run: |
                  just ci-test-unit

            - name: Run Format
              run: |
                  just ci-format

            - name: Run sort
              run: |
                  just ci-sort-imports

            - name: Publish Test Results
              uses: EnricoMi/publish-unit-test-result-action@v2
              if: always()
              with:
                  check_name: ${{ github.workflow }} Results
                  comment_title: ${{ github.workflow }} Results
                  files: |
                      *.xml
